version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    mem_limit: 512m
    cpus: "0.30"
    networks:
      - ecommerce-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    mem_limit: 1g
    cpus: "0.40"
    networks:
      - ecommerce-network


  backend:
    image: ghcr.io/sumit-shingari/ecommerce-platform/backend:latest
    container_name: backend
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    mem_limit: 1g
    cpus: "0.40"
    networks:
      - ecommerce-network


  frontend:
    image: ghcr.io/sumit-shingari/ecommerce-platform/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    mem_limit: 200m
    cpus: "0.20"
    networks:
      - ecommerce-network


networks:
  ecommerce-network:


volumes:
  mysql_data:
  es_data: